### ISSUE TITLE
Error trying to run fontmake on NotoSanAdlam ufo source

### ISSUE THREAD

**Issue by NeilSureshPatel** [googlefonts/noto-source#189]
I am working on bug fix for the Noto Sans Adlam that prevents the script from connecting. When I attempt to build with fontmake for testing, I get an "Assertion Error." This occurs the whether running fontmake on the designspace file or the individual UFOs. 

INFO:fontmake.font_project:Building OTF for NotoSansAdlam-Regular
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on NotoSansAdlam-Regular
INFO:ufo2ft.filters:Running RemoveOverlapsFilter on NotoSansAdlam-Regular
INFO:ufo2ft:Building OpenType tables
INFO:ufo2ft.postProcessor:Renaming glyphs to final production names
INFO:ufo2ft.postProcessor:Subroutinizing CFF table
INFO:fontmake.font_project:Saving master_otf/NotoSansAdlam-Regular.otf
Traceback (most recent call last):
  File "/Users/neilspatel/Documents/FontMake/Noto Sans Adlam New/env/bin/fontmake", line 10, in <module>
    sys.exit(main())
  File "/Users/neilspatel/Documents/FontMake/Noto Sans Adlam New/env/lib/python2.7/site-packages/fontmake/__main__.py", line 422, in main
    ufo_paths, is_instance=args.pop("masters_as_instances"), **args
  File "/Users/neilspatel/Documents/FontMake/Noto Sans Adlam New/env/lib/python2.7/site-packages/fontmake/font_project.py", line 1020, in run_from_ufos
    self.build_otfs(ufos, **kwargs)
  File "/Users/neilspatel/Documents/FontMake/Noto Sans Adlam New/env/lib/python2.7/site-packages/fontmake/font_project.py", line 307, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/Users/neilspatel/Documents/FontMake/Noto Sans Adlam New/env/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/Users/neilspatel/Documents/FontMake/Noto Sans Adlam New/env/lib/python2.7/site-packages/fontmake/font_project.py", line 619, in save_otfs
    self.subset_otf_from_ufo(otf_path, ufo)
  File "/Users/neilspatel/Documents/FontMake/Noto Sans Adlam New/env/lib/python2.7/site-packages/fontmake/font_project.py", line 686, in subset_otf_from_ufo
    assert len(ufo_order) == len(ot_order)
AssertionError

**Comment by punchcutter** [comment]
What's your command? I'm trying with various commands and not getting a problem. A few I tried with fontmake 2.1.0:
`fontmake -m NotoSansAdlam.designspace -o otf`
`fontmake -u NotoSansAdlam-Regular.ufo -o otf`

**Comment by NeilSureshPatel** [comment]
Those were the commands I was trying with the current Adlam files. I haven't try running an update on fontmake. Let me see if that's the issue.

**Comment by punchcutter** [comment]
Also it says you're on Python 2.7. I'm on 3.8.2. I'd recommend setting up a new 3.8 virtual env and pip installing fontmake there.

**Comment by NeilSureshPatel** [comment]
Thanks! Doing that now. Hadn't touched fontmake in a while and didn't realize how out of date my copy was.

**Comment by punchcutter** [comment]
Yes, lots of changes in fontTools and other parts of fontmake so Python 3 with latest fontmake is the best way to go.

**Comment by NeilSureshPatel** [comment]
That did it thanks!
